---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: backup_restic_minio
  pillars-from-files:
    backup_restic_minio.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
        - backup_restic_minio

platforms:
  - name: centos
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
          - backup_restic_minio

verifier:
  name: shell
  remote_exec: false
  command: .venv/bin/py.test -v  --connection=docker  --hosts=root@$KITCHEN_CONTAINER_ID --html=reports/$KITCHEN_INSTANCE.html --self-contained-html --junit-xml=reports/junit-$KITCHEN_INSTANCE.xml tests/integration/$KITCHEN_SUITE
