backup_restic_minio:
  update_images: false
  docker_bin: /usr/bin/docker

  postgres:
    image: rosscdh/docker-postgres-backup:12.3

  mysql:
    image: rosscdh/docker-mysql-backup:latest

  targets: []